version: '3.5'

services:
  nginx:
    image: nginx:1.13
    volumes:
      - ./etc_nginx/:/etc/nginx
    ports:
      - 80:80
  echo:
    image: tenzer/http-echo-test
  auth:
    image: nginx:1.13
    volumes:
      - ./auth/:/etc/nginx

